### ISSUE TITLE
Improve README for MethodsHub

### ISSUE THREAD

**Issue by rgaiacs** [gesiscss/WebBot#17]
Hi @yfiua,

Can you help me to improve the README for MethodsHub? The current render is available at http://svma-css-methodshub01.gesis.intra/github.com/gesiscss/WebBot/README/.

Can we replace the HTML tags with equivalent Markdown?

- [ ] https://github.com/gesiscss/WebBot/blob/486630b6b4a2ccea0494ce5b8509aa1caf89edbe/README.md?plain=1#L2
- [ ] https://github.com/gesiscss/WebBot/blob/486630b6b4a2ccea0494ce5b8509aa1caf89edbe/README.md?plain=1#L21

Thanks!

**Comment by yfiua** [comment]
@rgaiacs can you plz test now?

**Comment by yfiua** [comment]
fixed in [575a9d2](https://github.com/gesiscss/WebBot/commit/575a9d221bc3d4cf017afd735dd7eab046168bd3)
