### ISSUE TITLE
google infinity scroll

### ISSUE THREAD

**Issue by schochastics** [gesiscss/WebBot#18]
Seems that google now uses infinite scrolling for search pages (see https://github.com/gesistsa/webbotparseR/issues/15). How hard is that to fix? @yfiua @wanLo ideas?

**Comment by wanLo** [comment]
Bing image search already had infinite scrolling without page numbers, so maybe you could adapt [this implementation](https://github.com/gesiscss/WebBot/blob/575a9d221bc3d4cf017afd735dd7eab046168bd3/src/content/bot/BingBot.js#L55) to Google text results? I could also have a look at it after Easter… 🙂

**Comment by schochastics** [comment]
Thanks for the hint! If you think this is something you can do quickly AND you have time available, feel free to implement it 🙂. If not, please say so here so we can find another solution

**Comment by wanLo** [comment]
Sure, I can try and fix it next week, unless this is more urgent?

**Comment by schochastics** [comment]
nope, no urgency and thanks!

**Comment by yfiua** [comment]
Hi, nice you are following up. If you need help just ping me!

**Comment by wanLo** [comment]
I fixed the issue with GoogleBot in 54b18f8. I also fixed a minor issue with BaiduBot in 2623164 and another minor issue with SoBot in 131194c.
Among all the search engines implemented, Google, Bing, Yahoo, Baidu, So, and Sogou seem to be working as of right now. DuckDuckGo and Yandex.com are currently broken (see #19 and #20) and I unfortunately do not have the time to take care of this.

**Comment by schochastics** [comment]
Awesome thank you, this is more than I expected :)

**Comment by schochastics** [comment]
cc @jobreu

**Comment by jobreu** [comment]
Thx for the fix and making me aware of this! Much appreciated! 😊

**Comment by yfiua** [comment]
I managed to fix DuckDuckGo but not Yandex @wanLo @schochastics.

**Comment by mrwunderbar666** [comment]
I know this is annoying, but Google reverted to paginated results (e.g., read here: https://searchengineland.com/google-dropping-continuous-scroll-in-search-results-443529)

**Comment by yfiua** [comment]
> I know this is annoying, but Google reverted to paginated results (e.g., read here: https://searchengineland.com/google-dropping-continuous-scroll-in-search-results-443529)

reverted to paginated search
